language: ruby
rvm:
  - 1.9.3
  - 1.9.2
  - 1.8.7
  - rbx-18mode
  - rbx-19mode
gemfile:
  - gemfiles/rails-3-2.gemfile
  - gemfiles/rails-3-1.gemfile
  - gemfiles/rails-3-0.gemfile
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
